metadata := [[A, "prod", 1, "Producer"], [B, "bet", 1, "Designation / Product name"], [C, "descr", 1, "Detailed description"], [D, "fm_serviceclass", 1, "Service class limitation"], [E, "fm_width", mm, "Width of sharp metal plate"], [F, "fm_withscrew", 1, "Connection reinforced with screw"], [G, "f_v_0_k", N/mm^2, "Shear strength parallel to grain"], [H, "f_v_90_k", N/mm^2, "Shear strength normal to grain"], [I, "f_v_EG_k", N/mm^2, "Shear strength at end-grain edge"], [J, "k_ser_0_k", N/mm^3, "Slip modulus / Deformation factor parallel"], [K, "k_ser_90_k", N/mm^3, "Slip modulus / Deformation factor normal"], [L, "k_ser_EG_k", N/mm^3, "Slip modulus / Deformation factor edge"]]:
fm_withscrew := {"false", "true"}:
prod := table([("false")={"ROTHOBLAAS"},("true")={"ROTHOBLAAS"}]):
bet := table([("false", "ROTHOBLAAS")={"SHARP50", "SHARP50H"},("true", "ROTHOBLAAS")={"SHARP50", "SHARP50H"}]):
descr := table([("false", "ROTHOBLAAS", "SHARP50H")={"Sharp Metal High Density"},("false", "ROTHOBLAAS", "SHARP50")={"Sharp Metal Low Density"},("true", "ROTHOBLAAS", "SHARP50H")={"Sharp Metal High Density"},("true", "ROTHOBLAAS", "SHARP50")={"Sharp Metal Low Density"}]):
fm_serviceclass := table([("false", "ROTHOBLAAS", "SHARP50H")={2.0},("false", "ROTHOBLAAS", "SHARP50")={2.0},("true", "ROTHOBLAAS", "SHARP50H")={2.0},("true", "ROTHOBLAAS", "SHARP50")={2.0}]):
fm_width := table([("false", "ROTHOBLAAS", "SHARP50H")={50.0*Units:-Unit(mm)},("false", "ROTHOBLAAS", "SHARP50")={50.0*Units:-Unit(mm)},("true", "ROTHOBLAAS", "SHARP50H")={50.0*Units:-Unit(mm)},("true", "ROTHOBLAAS", "SHARP50")={50.0*Units:-Unit(mm)}]):
fm_fv0k := table([("false", "ROTHOBLAAS", "SHARP50H")={1.15*Units:-Unit(N/mm^2)},("false", "ROTHOBLAAS", "SHARP50")={.93*Units:-Unit(N/mm^2)},("true", "ROTHOBLAAS", "SHARP50H")={2.24*Units:-Unit(N/mm^2)},("true", "ROTHOBLAAS", "SHARP50")={2.02*Units:-Unit(N/mm^2)}]):
fm_fv90k := table([("false", "ROTHOBLAAS", "SHARP50H")={.51*Units:-Unit(N/mm^2)},("false", "ROTHOBLAAS", "SHARP50")={.2*Units:-Unit(N/mm^2)},("true", "ROTHOBLAAS", "SHARP50H")={2.42*Units:-Unit(N/mm^2)},("true", "ROTHOBLAAS", "SHARP50")={2.11*Units:-Unit(N/mm^2)}]):
fm_fvEGk := table([("false", "ROTHOBLAAS", "SHARP50H")={1.03*Units:-Unit(N/mm^2)},("false", "ROTHOBLAAS", "SHARP50")={1.03*Units:-Unit(N/mm^2)},("true", "ROTHOBLAAS", "SHARP50H")={1.92*Units:-Unit(N/mm^2)},("true", "ROTHOBLAAS", "SHARP50")={1.92*Units:-Unit(N/mm^2)}]):
fm_kser0k := table([("false", "ROTHOBLAAS", "SHARP50H")={6.47*Units:-Unit(N/mm^3)},("false", "ROTHOBLAAS", "SHARP50")={3.13*Units:-Unit(N/mm^3)},("true", "ROTHOBLAAS", "SHARP50H")={6.47*Units:-Unit(N/mm^3)},("true", "ROTHOBLAAS", "SHARP50")={3.13*Units:-Unit(N/mm^3)}]):
fm_kser90k := table([("false", "ROTHOBLAAS", "SHARP50H")={.9*Units:-Unit(N/mm^3)},("false", "ROTHOBLAAS", "SHARP50")={.65*Units:-Unit(N/mm^3)},("true", "ROTHOBLAAS", "SHARP50H")={.9*Units:-Unit(N/mm^3)},("true", "ROTHOBLAAS", "SHARP50")={.65*Units:-Unit(N/mm^3)}]):
fm_kserEGk := table([("false", "ROTHOBLAAS", "SHARP50H")={5.0*Units:-Unit(N/mm^3)},("false", "ROTHOBLAAS", "SHARP50")={4.19*Units:-Unit(N/mm^3)},("true", "ROTHOBLAAS", "SHARP50H")={5.0*Units:-Unit(N/mm^3)},("true", "ROTHOBLAAS", "SHARP50")={4.19*Units:-Unit(N/mm^3)}]):
